server:
  webhook-link : ""
format:
  username: "Athena Reporter"
  title: "Player Report"
  footer: "Crazy Network Banned Report"
  footer-images: "https://i.imgur.com/UomCbp7.jpg"
  avatar-url: "https://i.pinimg.com/564x/2c/41/42/2c41425598be8c992e66bcdb006af04c.jpg"
